#################################### DocumentCreatorAPI
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
RUN apt-get update && apt-get install -y apt-utils libgdiplus libc6-dev
WORKDIR /app
COPY ./ ./
ENTRYPOINT ["dotnet", "DocumentCreatorAPI.dll"]
