//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocumentCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;expressions&quot;:[{&quot;name&quot;:&quot;F01&quot;,&quot;cell&quot;:&quot;F3&quot;,&quot;expression&quot;:&quot;=VLOOKUP(source(\&quot;N3\&quot;,\&quot;RequestData.PS1016\&quot;),F27:G29,2,0)&quot;,&quot;isCollection&quot;:false,&quot;parent&quot;:&quot;&quot;,&quot;content&quot;:&quot;&quot;},{&quot;name&quot;:&quot;F02&quot;,&quot;cell&quot;:&quot;F4&quot;,&quot;expression&quot;:&quot;=source(\&quot;N4\&quot;,source(\&quot;N3\&quot;,\&quot;RequestData.PS1016\&quot;))&quot;,&quot;isCollection&quot;:false,&quot;parent&quot;:&quot;&quot;,&quot;content&quot;:&quot;_&quot;},{&quot;name&quot;:&quot;F03&quot;,&quot;cell&quot;:&quot;F5&quot;,&quot;expression&quot;:&quot;=MAPVALUE(N4,MAPVALUE(N3,\&quot;RequestData.PS1016\&quot;))&quot;,&quot;isCollection&quot;:false,&quot;parent&quot;:&quot;&quot;,&quot;content&quot;:&quot;&quot;},{&quot;name&quot;:&quot;F04&quot;,&quot;cell&quot;:&quot;F6&quot;,&quot;expression&quot;:&quot;=MAPVALUE(N3,\&quot;RequestData. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CanEvaluateMapAndGetUDF_json {
            get {
                return ResourceManager.GetString("CanEvaluateMapAndGetUDF_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ConvertTemplateWithImages_docx {
            get {
                object obj = ResourceManager.GetObject("ConvertTemplateWithImages_docx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CreateDocument_docx {
            get {
                object obj = ResourceManager.GetObject("CreateDocument_docx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;LogHeader&quot;:{&quot;RequestId&quot;:&quot;123456&quot;,&quot;Unit&quot;:&quot;123&quot;},&quot;RequestData&quot;:{&quot;ProductDescription&quot;:&quot;Προθεσμιακή με Bonus 3 Μηνών - Από Ευρώ 10.000&quot;,&quot;AccountNumber&quot;:&quot;923456789012345&quot;,&quot;SEPA&quot;:0.17,&quot;PS1014&quot;:3,&quot;PS1015&quot;:1,&quot;PS1016&quot;:&quot;MONTH&quot;,&quot;PS1053&quot;:&quot;START&quot;,&quot;PS1056&quot;:10000,&quot;F1041&quot;:5000,&quot;F1042&quot;:10000,&quot;InterestTable&quot;:[{&quot;Period&quot;:1,&quot;Interest&quot;:0.2,&quot;Points&quot;:500},{&quot;Period&quot;:3,&quot;Interest&quot;:0.25,&quot;Points&quot;:1000}]}}.
        /// </summary>
        internal static string CreateDocument_json {
            get {
                return ResourceManager.GetString("CreateDocument_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CreateDocument_xlsm {
            get {
                object obj = ResourceManager.GetObject("CreateDocument_xlsm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CreateMappingForTemplate_docx {
            get {
                object obj = ResourceManager.GetObject("CreateMappingForTemplate_docx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CreateMappingForTemplate_xlsm {
            get {
                object obj = ResourceManager.GetObject("CreateMappingForTemplate_xlsm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EvaluateForExcelExample01_docx {
            get {
                object obj = ResourceManager.GetObject("EvaluateForExcelExample01_docx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;expressions&quot;:[{&quot;name&quot;:&quot;F01&quot;,&quot;cell&quot;:&quot;J3&quot;,&quot;expression&quot;:&quot;=SYSDATE()&quot;,&quot;isCollection&quot;:false,&quot;parent&quot;:&quot;&quot;,&quot;content&quot;:&quot;&quot;},{&quot;name&quot;:&quot;F02&quot;,&quot;cell&quot;:&quot;J4&quot;,&quot;expression&quot;:&quot;=UPPER(RQD(\&quot;ProductDescription\&quot;))&quot;,&quot;isCollection&quot;:false,&quot;parent&quot;:&quot;&quot;,&quot;content&quot;:&quot;&quot;},{&quot;name&quot;:&quot;F03&quot;,&quot;cell&quot;:&quot;J5&quot;,&quot;expression&quot;:&quot;=RQD(\&quot;AccountNumber\&quot;)&quot;,&quot;isCollection&quot;:false,&quot;parent&quot;:&quot;&quot;,&quot;content&quot;:&quot;&quot;},{&quot;name&quot;:&quot;F04&quot;,&quot;cell&quot;:&quot;J6&quot;,&quot;expression&quot;:&quot;=LOWER(RQD(\&quot;PS1014\&quot;))&quot;,&quot;isCollection&quot;:false,&quot;parent&quot;:&quot;&quot;,&quot;content&quot;:&quot;&quot;},{&quot;name&quot;:&quot;F05&quot;,&quot;cell&quot;:&quot;J7&quot;,&quot;expres....
        /// </summary>
        internal static string EvaluateForExcelExample01_json {
            get {
                return ResourceManager.GetString("EvaluateForExcelExample01_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FindTemplateFields001_docx {
            get {
                object obj = ResourceManager.GetObject("FindTemplateFields001_docx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FindTemplateFields002_docx {
            get {
                object obj = ResourceManager.GetObject("FindTemplateFields002_docx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OpenXmlSpreadsheetTests001_xlsm {
            get {
                object obj = ResourceManager.GetObject("OpenXmlSpreadsheetTests001_xlsm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] UseForwardOwnCellValues_xlsm {
            get {
                object obj = ResourceManager.GetObject("UseForwardOwnCellValues_xlsm", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
