//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocumentCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;expressions&quot;:[{&quot;name&quot;:&quot;F01&quot;,&quot;cell&quot;:&quot;F3&quot;,&quot;expression&quot;:&quot;=VLOOKUP(source(\&quot;N3\&quot;,\&quot;RequestData.PS1016\&quot;),F27:G29,2,0)&quot;,&quot;isCollection&quot;:false,&quot;parent&quot;:&quot;&quot;,&quot;content&quot;:&quot;&quot;},{&quot;name&quot;:&quot;F02&quot;,&quot;cell&quot;:&quot;F4&quot;,&quot;expression&quot;:&quot;=source(\&quot;N4\&quot;,source(\&quot;N3\&quot;,\&quot;RequestData.PS1016\&quot;))&quot;,&quot;isCollection&quot;:false,&quot;parent&quot;:&quot;&quot;,&quot;content&quot;:&quot;_&quot;},{&quot;name&quot;:&quot;F03&quot;,&quot;cell&quot;:&quot;F5&quot;,&quot;expression&quot;:&quot;=MAPVALUE(N4,MAPVALUE(N3,\&quot;RequestData.PS1016\&quot;))&quot;,&quot;isCollection&quot;:false,&quot;parent&quot;:&quot;&quot;,&quot;content&quot;:&quot;&quot;},{&quot;name&quot;:&quot;F04&quot;,&quot;cell&quot;:&quot;F6&quot;,&quot;expression&quot;:&quot;=MAPVALUE(N3,\&quot;RequestData. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string can_evaluate_map_and_get_udf_json {
            get {
                return ResourceManager.GetString("can-evaluate-map-and-get-udf_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] convert_template_with_images_docx {
            get {
                object obj = ResourceManager.GetObject("convert-template-with-images_docx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] create_document_docx {
            get {
                object obj = ResourceManager.GetObject("create-document_docx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;LogHeader&quot;:{&quot;RequestId&quot;:&quot;123456&quot;,&quot;Unit&quot;:&quot;123&quot;},&quot;RequestData&quot;:{&quot;ProductDescription&quot;:&quot;Προθεσμιακή με Bonus 3 Μηνών - Από Ευρώ 10.000&quot;,&quot;AccountNumber&quot;:&quot;923456789012345&quot;,&quot;SEPA&quot;:0.17,&quot;PS1014&quot;:3,&quot;PS1015&quot;:1,&quot;PS1016&quot;:&quot;MONTH&quot;,&quot;PS1053&quot;:&quot;START&quot;,&quot;PS1056&quot;:10000,&quot;F1041&quot;:5000,&quot;F1042&quot;:10000,&quot;InterestTable&quot;:[{&quot;Period&quot;:1,&quot;Interest&quot;:0.2,&quot;Points&quot;:500},{&quot;Period&quot;:3,&quot;Interest&quot;:0.25,&quot;Points&quot;:1000}]}}.
        /// </summary>
        internal static string create_document_json {
            get {
                return ResourceManager.GetString("create-document_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] create_document_xlsm {
            get {
                object obj = ResourceManager.GetObject("create-document_xlsm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] create_mapping_for_template_docx {
            get {
                object obj = ResourceManager.GetObject("create-mapping-for-template_docx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] create_mapping_for_template_xlsm {
            get {
                object obj = ResourceManager.GetObject("create-mapping-for-template_xlsm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] evaluate_for_excel_example01_docx {
            get {
                object obj = ResourceManager.GetObject("evaluate-for-excel-example01_docx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;expressions&quot;:[{&quot;name&quot;:&quot;F01&quot;,&quot;cell&quot;:&quot;J3&quot;,&quot;expression&quot;:&quot;=SYSDATE()&quot;,&quot;isCollection&quot;:false,&quot;parent&quot;:&quot;&quot;,&quot;content&quot;:&quot;&quot;},{&quot;name&quot;:&quot;F02&quot;,&quot;cell&quot;:&quot;J4&quot;,&quot;expression&quot;:&quot;=UPPER(RQD(\&quot;ProductDescription\&quot;))&quot;,&quot;isCollection&quot;:false,&quot;parent&quot;:&quot;&quot;,&quot;content&quot;:&quot;&quot;},{&quot;name&quot;:&quot;F03&quot;,&quot;cell&quot;:&quot;J5&quot;,&quot;expression&quot;:&quot;=RQD(\&quot;AccountNumber\&quot;)&quot;,&quot;isCollection&quot;:false,&quot;parent&quot;:&quot;&quot;,&quot;content&quot;:&quot;&quot;},{&quot;name&quot;:&quot;F04&quot;,&quot;cell&quot;:&quot;J6&quot;,&quot;expression&quot;:&quot;=LOWER(RQD(\&quot;PS1014\&quot;))&quot;,&quot;isCollection&quot;:false,&quot;parent&quot;:&quot;&quot;,&quot;content&quot;:&quot;&quot;},{&quot;name&quot;:&quot;F05&quot;,&quot;cell&quot;:&quot;J7&quot;,&quot;expres....
        /// </summary>
        internal static string evaluate_for_excel_example01_json {
            get {
                return ResourceManager.GetString("evaluate-for-excel-example01_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] find_template_fields001_docx {
            get {
                object obj = ResourceManager.GetObject("find-template-fields001_docx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] find_template_fields002_docx {
            get {
                object obj = ResourceManager.GetObject("find-template-fields002_docx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] open_xml_spreadsheet_tests001_xlsm {
            get {
                object obj = ResourceManager.GetObject("open-xml-spreadsheet-tests001_xlsm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] simple_receipt_template_docx {
            get {
                object obj = ResourceManager.GetObject("simple-receipt-template_docx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] template_themis_docx {
            get {
                object obj = ResourceManager.GetObject("template-themis_docx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] use_forward_own_cell_values_xlsm {
            get {
                object obj = ResourceManager.GetObject("use-forward-own-cell-values_xlsm", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
